yarnPath: .yarn/releases/yarn-3.5.1.cjs
nodeLinker: node-modules
packageExtensions:
  jest-config@*:
    dependencies:
      ts-node: "*"
      jest-runtime: "*"
  jest-cli@*:
    dependencies:
      "@jest/reporters": "*"
      "@jest/console": "*"  
